version : '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=todo
    ports:
        - "5432:5432"
    volumes:
        - todoapp-db:/var/lib/postgresql/data
    logging:
        driver: "json-file"
        options:
            max-size: "1m"
            max-file: "3"
  app:
    build: .
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT
    links:
        - postgres
    depends_on:
        - postgres
    ports:
        - "8080:8080"
    logging:
        driver: "json-file"
        options:
            max-size: "1m"
            max-file: "3"

volumes:
    todoapp-db:

